services:
  frontend:
    container_name: frontend
    image: frontend-image
    build: ./frontend
    expose:
      - 5173
    networks:
      - fiscolia
    volumes:
      # - ./frontend/srcs/App.js:/app/src/App.jsx:Z
      # - ./frontend/srcs/index.css:/app/src/index.css:Z
      - ./frontend/srcs:/app/src:Z
    environment:
      - CHOWN=1


# TODO: PASSER NGINX EN SLIM
  nginx:
    container_name: nginx
    image: nginx-image
    build: ./server
    ports:
      - 80:80
    networks:
      - fiscolia
  backend-auth:
    container_name: backend-auth
    image: backend-auth-image
    build: ./backend-auth-login
    networks:
      - fiscolia

networks:
  fiscolia:
    name: fiscolia-network
    driver: bridge
