name: Fiscolia CI Checker

on: [push]

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debugging
        run : |
              echo "checking out code"
              ls -la
              echo "------------------------------"
              tree

      - name : Create env variables for docker environment
        env:
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}



      - name: Create .env file and secrets
        run: |
          echo "${{ secrets.DB_AUTH_PWD }}" > secrets/db_auth_pwd.txt
          echo "${{ secrets.DB_ROOT_PWD }}" > secrets/db_root_pwd.txt
          echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" > .env
          echo "PROXY_EXPOSED_PORT=${{ secrets.PROXY_EXPOSED_PORT }}" >> .env 
          echo "DB_AUTH_USER=${{ secrets.DB_AUTH_USER }}" >> .env
          echo "DB_AUTH_SECRETS=${{ secrets.DB_AUTH_SECRETS }}" >> .env
          echo "DB_AUTH_PORT=${{ secrets.DB_AUTH_PORT }}" >> .env
          echo "DB_AUTH_NAME=${{ secrets.DB_AUTH_NAME }}" >> .env
          echo "BACK_AUTH_PORT=${{ secrets.BACK_AUTH_PORT }}" >> .env
          echo "FRONT_PORT=${{ secrets.FRONT_PORT }}" >> .env
          echo "POSTGRES_PASSWORD_FILE=${{ secrets.POSTGRES_PASSWORD_FILE }}" >> .env
          echo "VERIFICATION .env FILE CONTENT"
          cat .env
          echo "VERIFICATION secrets FILE CONTENT"
          cat secrets/db_auth_pwd.txt
          cat secrets/db_root_pwd.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verification Python setup
        run : python --version

      - name : Build and start services
        run: make github-actions

      - name: Stop services and clean up
        if: always()
        run: make fclean