name: Fiscolia CI Checker

on: [push]

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        run : echo "checking out code"
              ls -la
              echo "------------------------------"
              tree

      - name: Create .env file and secrets
        run:
          mkdir -p secrets
          echo "${{ secrets.DB_AUTH_PWD }}" > secrets/db_auth_pwd.txt
          echo "${{ secrets.DB_ROOT_PWD }}" > secrets/db_root_pwd.txt
          echo "${{ secrets.PROXY_EXPOSED_PORT }}" >> .env 
          echo "${{ secrets.PROJECT_NAME }}" >> .env
          echo "${{ secrets.DB_AUTH_USER }}" >> .env
          echo "${{ secrets.DB_AUTH_SECRETS }}" >> .env
          echo "${{ secrets.DB_AUTH_PORT }}" >> .env
          echo "${{ secrets.DB_AUTH_NAME }}" >> .env
          echo "${{ secrets.BACK_AUTH_PORT }}" >> .env
          echo "${{ secrets.FRONT_PORT }}" >> .env
          echo "${{ secrets.POSTGRES_PASSWORD_FILE }}" >> .env
          echo "VERIFICATION .env FILE CONTENT"
          cat .env
          echo "VERIFICATION secrets FILE CONTENT"
          cat secrets/*

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        run : python --version

      - name : Build and start services
        run: make github-actions

      - name: Stop services and clean up
        if: always()
        run: make fclean